### ISSUE TITLE
SerialCon is a SerialPort -> no need to assign this to an Attribute.

### ISSUE THREAD

**Issue by yannicklamprecht** [DarkEyeDragon/LED_Controller#1]
https://github.com/DarkEyeDragon/LED_Controller/blob/master/LED_Controller/Serial/SerialCon.cs#L20

https://github.com/DarkEyeDragon/LED_Controller/blob/master/LED_Controller/Serial/SerialCon.cs#L24Use this.IsOpen instead or only IsOpen

**Comment by DarkEyeDragon** [comment]
Fixed in https://github.com/DarkEyeDragon/LED_Controller/commit/2e6bda932921f3ce07d7085a6920897ac791bc71.

**Comment by yannicklamprecht** [comment]
https://github.com/DarkEyeDragon/LED_Controller/blob/master/LED_Controller/Serial/SerialCon.cs#L20
can be removed and this as well:
https://github.com/DarkEyeDragon/LED_Controller/blob/master/LED_Controller/Serial/SerialCon.cs#L13

No need to access SerialCon#SerialPort when the instance of SerialCon as a SerialPort.

**Comment by DarkEyeDragon** [comment]
Addressed in 37428c24ef863c355c406b96fbf190f4bcacc8ea.
